### ISSUE TITLE
VFO Mode

### ISSUE THREAD

**Issue by GreeneEye** [OEFW-community/RT-890-custom-firmware#64] opened 2024-01-19 20:16 UTC
Name from last memory mode locks in when switching to VFO mode, though you can change to any frequency the name stays as if in memory mode still.

**Comment by reppad** [comment] 2024-01-21 14:38
Hi,

Are you just changing from Channel mode to VFO mode or this issue is only when you follow the following path ?
Channel mode -> launch spectrum -> Jump to VFO with menu key

If your case is the one with spectrum, the issue was [resolved](https://github.com/OEFW-community/RT-890-custom-firmware/commit/bb8f39f419f83097956fe36e79cdb9b5ee0f171a), using the [last build](https://github.com/OEFW-community/RT-890-custom-firmware/actions/runs/7309934527) from main will solve it.

If it is not this case please can you provide more infos, like detailed steps to reproduce, video...

Thank for your report.

**Comment by GreeneEye** [comment] 2024-01-22 19:52
I believe that is the build I'm running, but I will run that one today just to be sure. I will report back with results, thank you!

**Comment by GreeneEye** [comment] 2024-01-22 20:06
That is the current build I am running. 
The radio has selected two channel names (no idea why) to display in VFO mode no matter the frequency I am on or in. These names do not change in VFO, and I have no ability to change or remove them in VFO through the channel memory settings in the menu. 

The issue is switching from Memory mode -> VFO mode
I have not played around with spectrum mode too much, so I don't really know if it's an issue there. 

![D6AFC4DB-9A1B-4609-8E21-441C339F582A](https://github.com/OEFW-community/RT-890-custom-firmware/assets/156963856/bf0adbb7-eb72-41ce-8219-8478f278c7f1)

You guys are awesome!

**Comment by Tunas1337** [comment] 2024-01-23 21:04
Hi GreeneEye, this is a feature, not a bug. I'm not kidding -- it happens in the stock FW as well.
The VFOs are just channels 1000 and 1001, and they're rename-able just like any channel.

**Comment by Tunas1337** [comment] 2024-01-23 21:05
For what it's worth, we might make this a makefile flag, but other than that, I'm closing it as "not planned."

**Closed as not planned by Tunas1337** 2024-01-23 21:05 UTC

**Comment by GreeneEye** [comment] 2024-01-23 21:06
I would have never even guessed that. Thank you so much for the replay and clarification!

**Comment by reppad** [comment] 2024-01-24 01:24
Yes, VFOs can be named like any channel and changing the frequency does not erase the name.
On the other hand, I don't understand how the name was defined if it is not intentional or why you can't change it from the menu as is the case for channels?

**Comment by GreeneEye** [comment] 2024-01-24 02:01
..... Oh man, if that's true?!? 

Woot! I was able to remane the channel, but only after reflashing. Ended up flashing the colored version that was released today.
